export type PropertyUpdateData = {
  propertyId: string,
  streetnumber: string,
  streetname: string,
  suburb: string,
  province: string,
  postcode: string,
  description: string,
  summaryDescription: string,
  bathrooms: number,
  bedrooms: number,
  parking: number,
  features: string[],
  type: string,
  area: number,
  landlordId: string,
};