export enum NavigationPath {
  Home = "/",
  AgentDashboard = "/agent-dashboard",
  AgentProperties = "/agent-properties",
  AgentCalendar = "/agent-calendar",
  AgentMessages = "/agent-messages",
  AgentTasks = "/agent-tasks",
  LandlordDashboard = "/landlord-dashboard",
  LandlordProperties = "/landlord-properties",
  LandlordCalendar = "/landlord-calendar",
  LandlordTasks = "/landlord-tasks",
  PropertyListing = "/test",
  Settings = "/settings",
  PropertyForm = "/propertyform",
  Login = "/login",
  Profile = "/profile",
  Signup = "/signup",
  TenantDashboard = "/tenant-dashboard",
  TenantProperty = "/tenant-property",
  TenantCalendar = "/tenant-calendar",
  TenantMaintenance = "/tenant-maintenance",
  TenantMessages = "/tenant-messages",
  TenantDocuments = "/tenant-documents",
  TenantSearchProperties = "/tenant-search-properties",
}
