import { Meteor } from "meteor/meteor";
import { Mongo } from "meteor/mongo";
import { AgentDocument } from "/app/server/database/user/models/AgentDocument";
import { MeteorMethodIdentifier } from "/app/shared/meteor-method-identifier";
import { AgentCollection } from "/app/server/database/user/user-collections";

// -- INSERT AGENT --
const agentInsertMethod = {
  [MeteorMethodIdentifier.AGENT_INSERT]: async (
    data: Omit<AgentDocument, "createdAt" | "_id"> // omitting both id and createdat to be generated by the db
  ): Promise<string> => {
    const newAgent: Mongo.OptionalId<AgentDocument> = {
      ...data,
      createdAt: new Date(),
    };

    return await AgentCollection.insertAsync(newAgent);
  },
}


Meteor.methods({
  ...agentInsertMethod,
});
