import { Meteor } from "meteor/meteor";
import { Mongo } from "meteor/mongo";
import { TenantDocument } from "/app/server/database/user/models/TenantDocument";
import { TenantCollection } from "/app/server/database/user/user-collections";
import { MeteorMethodIdentifier } from "/app/shared/meteor-method-identifier";

// -- INSERT TENANT --
const tenantInsertMethod = {
  [MeteorMethodIdentifier.TENANT_INSERT]: async (
    data: Omit<TenantDocument, "createdAt" | "_id"> // omitting both id and createdat to be generated by the db
  ): Promise<string> => {
    const newTenant: Mongo.OptionalId<TenantDocument> = {
      ...data,
      createdAt: new Date(),
    };

    return await TenantCollection.insertAsync(newTenant);
  },
}


Meteor.methods({
  ...tenantInsertMethod,
});