export enum MeteorMethodIdentifier {
  TASK_INSERT = "tasks.insert",
  TASK_GET = "tasks.getOne",
  TASK_GET_PENDING_COUNT = "tasks.getPendingCount",
  TASK_GET_PENDING_LIST = "tasks.getPendingList",
  BLOB_UPLOAD_FILE = "blobs.uploadFile",
  BLOB_UPLOAD_FILES = "blobs.uploadFiles",
  PROPERTY_GET = "properties.getOne",
  PROPERTY_GET_COUNT = "properties.getCount",
  PROPERTY_GET_LIST = "properties.getList",
  LISTING_GET_FOR_PROPERTY = "listings.getForProperty",
  USER_REGISTER = "user.register",
  USER_ACCOUNT_INSERT = "users.insert",
  USER_ACCOUNT_GET = "users.getOne",
  AGENT_INSERT = "agents.insert",
  AGENT_GET = "agents.getOne",
  TENANT_INSERT = "tenants.insert",
  TENANT_GET = "tenants.getOne",
  LANDLORD_INSERT = "landlords.insert",
  LANDLORD_GET = "landlords.getOne",
}
