import { PropertyMapUiState } from "../../common/property-components/PropertyMap";
import { Landlord } from "/app/client/library-modules/domain-models/user/Landlord";
import { ListingStatusPillVariant } from "/app/client/ui-modules/property-listing-page/components/ListingStatusPill";
import { PropertyStatusPillVariant } from "/app/client/ui-modules/property-listing-page/components/ListingSummary";
import { InspectionBookingListUiState } from "/app/client/ui-modules/property-listing-page/components/PropertyInspections";

export type PropertyListingPageUiState = {
  agentId: string;
  propertyId: string;
  propertyLandlordId: string;
  streetNumber: string;
  street: string;
  suburb: string;
  province: string;
  postcode: string;
  apartmentNumber?: string;
  summaryDescription: string;
  areaValue: number
  propertyStatusText: string;
  propertyStatusPillVariant: PropertyStatusPillVariant;
  propertyDescription: string;
  propertyFeatures: string[];
  propertyFeatureIds: string[];
  propertyType: string;
  propertyLandArea: string;
  propertyBathrooms: string;
  propertyParkingSpaces: string;
  propertyBedrooms: string;
  propertyPrice: string;
  monthlyRent: number;
  mapUiState: PropertyMapUiState;
  inspectionBookingUiStateList: InspectionBookingListUiState[];
  inspectionTimes: { start_time: string; end_time: string }[];
  bookedPropertyListingInspections: number[];
  listingImageUrls: string[];
  listingStatusText: string;
  listingStatusPillVariant: ListingStatusPillVariant;
  leaseTerm: string;
  shouldDisplayListingStatus: boolean;
  shouldDisplaySubmitDraftButton: boolean;
  shouldDisplayReviewTenantButton: boolean;
  shouldDisplayEditListingButton: boolean;
  shouldShowLoadingState: boolean;
  landlords: Landlord[];
  isSubmittingDraft: boolean;
  currentPropertyId?: string;
};